version: 1
services:
  - type: worker
    name: file-request-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: STORAGE_CHANNEL
        sync: false
      - key: PORT
        value: 8000
    autoScaling:
      enabled: false
